# Generated by Django 4.0.4 on 2022-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('user', 'Client'), ('support', 'Support')], default='user', max_length=15),
        ),
    ]
