version: "3"

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: supportee_app
  volumes:
   - .:/code
  env_file:
   - db_keys.txt
  ports:
   - "8000:8000"
  depends_on:
   - db
  command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

 db:
  image: postgres:latest
  container_name: supportee_postgres
  env_file:
   - db_keys.txt
  ports:
   - "5432:5432"

 redis:
  image: redis:latest
  container_name: supportee_redis_db

 celery:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: supportee_celery_w
  volumes:
   - .:/code
  env_file:
   - db_keys.txt
  depends_on:
   - redis
  ports:
   - '5555:5555'
  command: bash -c 'celery -A suptee worker -l info & celery -A suptee flower'