version: "3"

services:
 web:
  build:
   context: .
   dockerfile: Dockerfile
  container_name: supportee_app
  volumes:
   - .:/code
  env_file:
   - db_keys.txt
  ports:
   - "8000:8000"
  depends_on:
   - db
  command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"

 db:
  image: postgres:latest
  container_name: supportee_postgres
  volumes:
   - ./data/db:/var/lib/postgresql/data
  env_file:
   - db_keys.txt
  ports:
   - "5432:5432"
