# Generated by Django 4.0.4 on 2022-04-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ticket', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('solved', 'Решенные'), ('unsolved', 'Нерешенные'), ('frozen', 'Замороженные')], default='unsolved', max_length=15)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
