# Generated by Django 4.0.4 on 2022-05-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_ticket_num_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('solved', 'Solved tickets'), ('unsolved', 'Unsolved tickets'), ('frozen', 'Frozen tickets')], default='unsolved', max_length=15),
        ),
    ]
